[project]
authors = ["Lee Katz"]
channels = ["conda-forge", "bioconda"]
description = "Make bootstraps from MLST profiles"
name = "bsMLST"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
grapetree = ">=2.1,<3"
gotree = ">=0.4.5,<0.5"
perl = ">=5.32.1,<6"
